/*

 MAZEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\agini\Downloads\maze.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maze_mapWidth 20
#define maze_mapHeight 18
#define maze_mapBank 0

extern unsigned char maze_map[];

#define maze_map_twoWidth 20
#define maze_map_twoHeight 18
#define maze_map_twoBank 0

extern unsigned char maze_map_two[];

#define maze_map_threeWidth 20
#define maze_map_threeHeight 18
#define maze_map_threeBank 0

extern unsigned char maze_map_three[];

/* End of MAZEMAP.H */
